LMS_PROJECT/LMS/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views, user_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin", admin.site.urls),
    path("base", views.BASE, name="base"),
    path("404", views.PAGE_NOT_FOUND, name="404"),
    path("", views.HOME, name="home"),
    path("course", views.SINGLE_COURSE, name="single_course"),
    path("course/filter-data", views.filter_data, name="filter-data"),
    path("course/<slug:slug>", views.COURSE_DETAILS, name="course_details"),
    path("search", views.SEARCH_COURSE, name="search_course"),
    path("my-course", views.MY_COURSE, name="my_course"),
    path("course/watch_course/<slug:slug>", views.WATCH_COURSE, name="watch_course"),
    path("contact", views.CONTACT_US, name="contact_us"),
    path("about", views.ABOUT_US, name="about_us"),
    path("accounts", include("django.contrib.auth.urls")),
    path("accounts/register", user_login.REGISTER, name="register"),
    path("accounts/doLogin", user_login.DO_LOGIN, name="doLogin"),
    path("accounts/doLogout/", user_login.DO_LOGOUT, name="doLogout"),
    path("accounts/profile", user_login.PROFILE, name="profile"),
    path("accounts/profile/update", user_login.PROFILE_UPDATE, name="profile_update"),
    path("checkout/<slug:slug>", views.CHECKOUT, name="checkout"),
    path("verify_payment", views.VERIFY_PAYMENT, name="verify_payment"),
    path(
        "update_video_watch_status/",
        views.update_video_watch_status,
        name="update_video_watch_status",
    ),
    path(
        "check_video_watch_status/",
        views.check_video_watch_status,
        name="check_video_watch_status",
    ),
    path("quiz/<int:video_id>/", views.quiz_detail, name="quiz_detail"),
    path("quiz/<int:quiz_id>/submit/", views.submit_quiz, name="submit_quiz"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LMS_PROJECT/app/models.py
from django.db import models
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone


# Create your models here.
class Categories(models.Model):
    icon = models.CharField(max_length=200, null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

    def get_all_category(self):
        return Categories.objects.all().order_by("id")


class Author(models.Model):
    author_profile = models.ImageField(upload_to="Media/author")
    name = models.CharField(max_length=100, null=True)
    author_title = models.CharField(max_length=100, null=True)
    about_author = models.TextField(null=True)

    def __str__(self):
        return self.name


class Level(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Language(models.Model):
    language = models.CharField(max_length=100)

    def __str__(self):
        return self.language


class Course(models.Model):
    STATUS = (
        ("PUBLISH", "PUBLISH"),
        ("DRAFT", "DRAFT"),
    )

    featured_image = models.ImageField(upload_to="Media/featured_image", null=True)
    featured_video = models.CharField(max_length=300, null=True)
    title = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Categories, on_delete=models.CASCADE)
    language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True)
    deadline = models.CharField(max_length=100, null=True)
    level = models.ForeignKey(Level, on_delete=models.CASCADE, null=True)
    description = models.TextField()
    price = models.IntegerField(null=True, default=0)
    discount = models.IntegerField(null=True)
    slug = models.SlugField(default="", max_length=255, null=True, blank=True)
    status = models.CharField(choices=STATUS, max_length=100, null=True)
    certificate = models.CharField(null=True, default=False, max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("course_details", kwargs={"slug": self.slug})


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Course.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)


pre_save.connect(pre_save_post_receiver, Course)


class What_you_learn(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points


class Requirements(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    points = models.CharField(max_length=500)

    def __str__(self):
        return self.points


class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name + " - " + self.course.title


# Quiz model
class Quiz(models.Model):
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title


# QuizQuestion model
class QuizQuestion(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="questions")
    question = models.CharField(max_length=500)
    option_1 = models.CharField(max_length=200)
    option_2 = models.CharField(max_length=200)
    option_3 = models.CharField(max_length=200)
    option_4 = models.CharField(max_length=200)
    correct_answer = (
        models.IntegerField()
    )  # Index of the correct option (1, 2, 3, or 4)

    def __str__(self):
        return self.question


class Video(models.Model):
    serial_number = models.IntegerField(null=True)
    thumbnail = models.ImageField(upload_to="Media/Yt_Thumbnail", null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    # youtube_id = models.CharField(max_length=200)
    video_file = models.FileField(upload_to="Media/Videos", null=True, blank=True)
    time_duration = models.IntegerField(null=True)
    preview = models.BooleanField(default=False)
    quiz = models.ForeignKey(
        Quiz, on_delete=models.SET_NULL, null=True, blank=True, related_name="videos"
    )

    def __str__(self):
        return self.title


class UserCourse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    paid = models.BooleanField(default=0)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.first_name + " - " + self.course.title


class Payment(models.Model):
    order_id = models.CharField(max_length=100, null=True, blank=True)
    payment_id = models.CharField(max_length=100, null=True, blank=True)
    user_course = models.ForeignKey(UserCourse, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, null=True)
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.first_name + "--" + self.course.title


STATUS_CHOICES = (
    ("not_started", "Not Started"),
    ("in_progress", "In Progress"),
    ("completed", "Completed"),
)


class UserVideoWatch(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    watched_at = models.DateTimeField(auto_now_add=True)
    watch_status = models.CharField(
        choices=STATUS_CHOICES, max_length=20, default="not_started"
    )
    progress = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user.first_name} - {self.video.title} ({self.watch_status})"


class UserQuizScore(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()
    total = models.IntegerField()
    percentage = models.FloatField()
    last_attempted = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ('user', 'quiz')  # Ensures a unique record for each user-quiz pair

LMS_PROJECT/templates/course/my_course.html
{% extends 'base.html' %}

{% block title %}
My Courses
{% endblock title %}

{% load static %}
{% load course_tags %}


{% block content %}
<!-- PAGE TITLE
    ================================================== -->
<header class="py-8 py-md-11" style="background-image: none;">
    <div class="container text-center py-xl-2">
        <h1 class="display-4 fw-semi-bold mb-0">Enrolled Courses</h1>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb breadcrumb-scroll justify-content-center">
                <li class="breadcrumb-item">
                    <a class="text-gray-800" href="{% url 'home' %}">
                        Home
                    </a>
                </li>
                <li class="breadcrumb-item text-gray-800 active" aria-current="page">
                    My Courses
                </li>
            </ol>
        </nav>
    </div>
    <!-- Img -->
    <img class="d-none img-fluid" src="{% static '...html' %}" alt="...">
</header>


<!-- CONTROL BAR
    ================================================== -->
<div class="container mb-6 mb-xl-8 z-index-2">
   
    <div class="d-xl-flex align-items-center">
        <p class="mb-xl-0">Courses you have Enrolled </p>
    </div>
</div>

<!-- COURSE LIST V1
    ================================================== -->
<div class="container pb-4 pb-xl-7">
    {% include 'components/msg.html' %}
    <div class="row row-cols-md-2 row-cols-xl-3 mb-6 mb-xl-3">
        {% for i in course %}
        <!-- ///////////////////////////////////////////////////////////////////////////////////////////// -->
        <div class="col-md pb-4 pb-md-7">
            <!-- Card -->
            <div class="card border shadow p-2 lift sk-fade">
                <!-- Image -->
                <div class="card-zoom position-relative">
                    <div class="badge-float sk-fade-top top-0 right-0 mt-4 me-4">
                        <a href="{{i.course.get_absolute_url}}"
                            class="btn btn-xs btn-dark text-white rounded-circle lift opacity-dot-7 me-1 p-2 d-inline-flex justify-content-center align-items-center w-36 h-36">
                            <!-- Icon -->
                            <svg width="18" height="18" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M17.8856 8.64995C17.7248 8.42998 13.8934 3.26379 8.99991 3.26379C4.10647 3.26379 0.274852 8.42998 0.114223 8.64974C-0.0380743 8.85843 -0.0380743 9.14147 0.114223 9.35016C0.274852 9.57013 4.10647 14.7363 8.99991 14.7363C13.8934 14.7363 17.7248 9.5701 17.8856 9.35034C18.0381 9.14169 18.0381 8.85843 17.8856 8.64995ZM8.99991 13.5495C5.39537 13.5495 2.27345 10.1206 1.3493 8.99965C2.27226 7.87771 5.38764 4.4506 8.99991 4.4506C12.6043 4.4506 15.726 7.8789 16.6505 9.00046C15.7276 10.1224 12.6122 13.5495 8.99991 13.5495Z"
                                    fill="currentColor" />
                                <path
                                    d="M8.9999 5.43958C7.03671 5.43958 5.43945 7.03683 5.43945 9.00003C5.43945 10.9632 7.03671 12.5605 8.9999 12.5605C10.9631 12.5605 12.5603 10.9632 12.5603 9.00003C12.5603 7.03683 10.9631 5.43958 8.9999 5.43958ZM8.9999 11.3736C7.69103 11.3736 6.62629 10.3089 6.62629 9.00003C6.62629 7.6912 7.69107 6.62642 8.9999 6.62642C10.3087 6.62642 11.3735 7.6912 11.3735 9.00003C11.3735 10.3089 10.3088 11.3736 8.9999 11.3736Z"
                                    fill="currentColor" />
                            </svg>

                        </a>
                        <a href="{{i.course.get_absolute_url}}"
                            class="btn btn-xs btn-dark text-white rounded-circle lift opacity-dot-7 p-2 d-inline-flex justify-content-center align-items-center w-36 h-36">
                            <!-- Icon -->
                            <svg width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M11.2437 1.20728C10.0203 1.20728 8.87397 1.66486 7.99998 2.48357C7.12598 1.66486 5.97968 1.20728 4.7563 1.20728C2.13368 1.20728 0 3.341 0 5.96366C0 7.2555 0.425164 8.52729 1.26366 9.74361C1.91197 10.6841 2.80887 11.5931 3.92937 12.4454C5.809 13.8753 7.66475 14.6543 7.74285 14.6867L7.99806 14.7928L8.25384 14.6881C8.33199 14.6562 10.1889 13.8882 12.0696 12.4635C13.1907 11.6142 14.0881 10.7054 14.7367 9.7625C15.575 8.54385 16 7.26577 16 5.96371C16 3.341 13.8663 1.20728 11.2437 1.20728ZM8.00141 13.3353C6.74962 12.7555 1.33966 10.0142 1.33966 5.96366C1.33966 4.07969 2.87237 2.54698 4.75634 2.54698C5.827 2.54698 6.81558 3.03502 7.46862 3.88598L8.00002 4.57845L8.53142 3.88598C9.18446 3.03502 10.173 2.54698 11.2437 2.54698C13.1276 2.54698 14.6604 4.07969 14.6604 5.96366C14.6603 10.0433 9.25265 12.7613 8.00141 13.3353Z"
                                    fill="currentColor" />
                            </svg>

                        </a>
                    </div>

                    <a href="{{i.course.get_absolute_url}}" class="card-img sk-thumbnail d-block">
                        <img class="rounded shadow-light-lg" src="{{i.course.featured_image}}" alt="...">
                    </a>

                    <span
                        class="badge sk-fade-bottom badge-lg badge-orange badge-pill badge-float bottom-0 left-0 mb-4 ms-4">
                        <span class="text-white text-uppercase fw-bold font-size-xs">BEST SELLER</span>
                    </span>
                </div>

                <!-- Footer -->
                <div class="card-footer px-2 pb-2 mb-1 pt-4 position-relative">
                    <a href="#" class="d-block">
                        <div
                            class="avatar sk-fade-right avatar-xl badge-float position-absolute top-0 right-0 mt-n6 me-5 rounded-circle shadow border border-white border-w-lg">
                            <img src="{{i.course.author.author_profile}}" alt="..." class="avatar-img rounded-circle">
                        </div>
                    </a>

                    <!-- Preheading -->
                    <a href="#"><span
                            class="mb-1 d-inline-block text-gray-800">{{i.course.category}}</span></a>

                    <!-- Heading -->
                    <div class="position-relative">
                        <a href="course-single-v2.html" class="d-block stretched-link">
                            <h4 class="line-clamp-2 h-md-48 h-lg-58 me-md-6 me-lg-10 me-xl-4 mb-2">{{i.course.title}}</h4>
                        </a>

                        <div class="d-lg-flex align-items-end flex-wrap mb-n1">
                            <div class="star-rating mb-2 mb-lg-0 me-lg-3">
                                <div class="rating" style="width:50%;"></div>
                            </div>

                            <div class="font-size-sm">
                                <span>5.45 (5.8k+ reviews)</span>
                            </div>
                        </div>

                        <div class="row mx-n2 align-items-end">
                            <div class="col px-2">
                                <ul class="nav mx-n3">
                                    <li class="nav-item px-3">
                                        <div class="d-flex align-items-center">
                                            <div class="me-2 d-flex icon-uxs text-secondary">
                                                <!-- Icon -->
                                                <svg width="20" height="20" viewBox="0 0 20 20" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <path
                                                        d="M17.1947 7.06802L14.6315 7.9985C14.2476 7.31186 13.712 6.71921 13.0544 6.25992C12.8525 6.11877 12.6421 5.99365 12.4252 5.88303C13.0586 5.25955 13.452 4.39255 13.452 3.43521C13.452 1.54098 11.9124 -1.90735e-06 10.0197 -1.90735e-06C8.12714 -1.90735e-06 6.58738 1.54098 6.58738 3.43521C6.58738 4.39255 6.98075 5.25955 7.61414 5.88303C7.39731 5.99365 7.1869 6.11877 6.98502 6.25992C6.32752 6.71921 5.79178 7.31186 5.40787 7.9985L2.8447 7.06802C2.33612 6.88339 1.79688 7.26044 1.79688 7.80243V16.5178C1.79688 16.8465 2.00256 17.14 2.31155 17.2522L9.75312 19.9536C9.93073 20.018 10.1227 20.0128 10.2863 19.9536L17.7278 17.2522C18.0368 17.14 18.2425 16.8465 18.2425 16.5178V7.80243C18.2425 7.26135 17.704 6.88309 17.1947 7.06802ZM10.0197 1.5625C11.0507 1.5625 11.8895 2.40265 11.8895 3.43521C11.8895 4.46777 11.0507 5.30792 10.0197 5.30792C8.98866 5.30792 8.14988 4.46777 8.14988 3.43521C8.14988 2.40265 8.98866 1.5625 10.0197 1.5625ZM9.23844 18.1044L3.35938 15.9703V8.91724L9.23844 11.0513V18.1044ZM10.0197 9.67255L6.90644 8.54248C7.58164 7.51892 8.75184 6.87042 10.0197 6.87042C11.2875 6.87042 12.4577 7.51892 13.1329 8.54248L10.0197 9.67255ZM16.68 15.9703L10.8009 18.1044V11.0513L16.68 8.91724V15.9703Z"
                                                        fill="currentColor" />
                                                </svg>

                                            </div>
                                            <div class="font-size-sm">{{i.course.video_set.all.count}} Lectures</div>
                                        </div>
                                    </li>
                                    <li class="nav-item px-3">
                                        <div class="d-flex align-items-center">
                                            <div class="me-2 d-flex icon-uxs text-secondary">
                                                <!-- Icon -->
                                                <svg width="16" height="16" viewBox="0 0 16 16"
                                                    xmlns="http://www.w3.org/2000/svg">
                                                    <path
                                                        d="M14.3164 4.20996C13.985 4.37028 13.8464 4.76904 14.0067 5.10026C14.4447 6.00505 14.6667 6.98031 14.6667 8C14.6667 11.6759 11.6759 14.6667 8 14.6667C4.32406 14.6667 1.33333 11.6759 1.33333 8C1.33333 4.32406 4.32406 1.33333 8 1.33333C9.52328 1.33333 10.9543 1.83073 12.1387 2.77165C12.4259 3.00098 12.846 2.95296 13.0754 2.66471C13.3047 2.37663 13.2567 1.95703 12.9683 1.72803C11.5661 0.613607 9.8016 0 8 0C3.58903 0 0 3.58903 0 8C0 12.411 3.58903 16 8 16C12.411 16 16 12.411 16 8C16 6.77767 15.7331 5.60628 15.2067 4.51969C15.0467 4.18766 14.6466 4.04932 14.3164 4.20996Z"
                                                        fill="currentColor" />
                                                    <path
                                                        d="M7.99967 2.66663C7.63167 2.66663 7.33301 2.96529 7.33301 3.33329V7.99996C7.33301 8.36796 7.63167 8.66663 7.99967 8.66663H11.333C11.701 8.66663 11.9997 8.36796 11.9997 7.99996C11.9997 7.63196 11.701 7.33329 11.333 7.33329H8.66634V3.33329C8.66634 2.96529 8.36768 2.66663 7.99967 2.66663Z"
                                                        fill="currentColor" />
                                                </svg>

                                            </div>
                                            <div class="font-size-sm">{{time_duration.sum}} min</div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            {% discount_calculation i.course.price i.course.discount as discounted_price %}
                            {% if discounted_price == 0 %}
                            <div class="col-auto px-2 text-right">
                                <del class="font-size-sm">₹{{i.course.price}}</del>
                                <ins class="h4 mb-0 d-block mb-lg-n1"><span class="badge badge-primary">Free</span></ins>
                                <!-- <ins class="h4 mb-0 d-block mb-lg-n1">₹{{i.course.price}}</ins> -->
                            </div>
                            {% else %}
                            <div class="col-auto px-2 text-right">
                                <del class="font-size-sm">₹{{i.course.price}}</del>
                                <!-- <ins class="h4 mb-0 d-block mb-lg-n1"><span class="badge badge-primary">Free</span></ins> -->
                                <ins class="h4 mb-0 d-block mb-lg-n1">₹{{discounted_price}}</ins>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    
</div>
{% endblock content %}